files:
  ignore:
    - 'node_modules/**/*.scss'
    - 'tests/**/*.scss'
  include:
    - 'wp-content/themes/*/styles/**/*.scss'

rules:
  hex-notation:
    - 1
    - style: uppercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 1
    - include: true
  no-trailing-zero:
    - 1
    - false
